version: '3'

services:
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"

  application:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: 'mongodb://mongo:27017'