apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    storage: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      storage: mongo
  template:
    metadata:
      labels:
        storage: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    storage: mongo
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    storage: mongo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-depl
  labels:
    service-name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      service-name: url-shortener
  template:
    metadata:
      labels:
        service-name: url-shortener
    spec:
      containers:
        - name: api
          image: lfyuomrgylo/url-shortener:v1
          env:
            - name: MONGO_URL
              value: mongodb://mongo-service:27017
          ports:
            - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  labels:
    service-name: url-shortener
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
  selector:
    service-name: url-shortener
